.TH "Physics.Collision.CollisionPair" 3 "2022年 十一月 2日 星期三" "PhysicsWorld" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Physics.Collision.CollisionPair
.SH SYNOPSIS
.br
.PP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "\fBCollisionObject\fP \fBfirst\fP"
.br
.ti -1c
.RI "\fBCollisionObject\fP \fBsecond\fP"
.br
.ti -1c
.RI "Vector3 \fBpenetrateVec\fP"
.br
.in -1c
.SH "类成员变量说明"
.PP 
.SS "\fBCollisionObject\fP Physics\&.Collision\&.CollisionPair\&.first"

.SS "Vector3 Physics\&.Collision\&.CollisionPair\&.penetrateVec"

.SS "\fBCollisionObject\fP Physics\&.Collision\&.CollisionPair\&.second"


.SH "作者"
.PP 
由 Doyxgen 通过分析 PhysicsWorld 的 源代码自动生成\&.
