.TH "Physics.Collision.Model.AABB" 3 "2022年 十一月 2日 星期三" "PhysicsWorld" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Physics.Collision.Model.AABB
.SH SYNOPSIS
.br
.PP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBAABB\fP (Vector3 \fBlowerBound\fP, Vector3 \fBupperBound\fP)"
.br
.ti -1c
.RI "void \fBApply\fP (Vector3 lower, Vector3 upper)"
.br
.in -1c
.SS "属性"

.in +1c
.ti -1c
.RI "Vector3 \fBlowerBound\fP\fC [get, private set]\fP"
.br
.ti -1c
.RI "Vector3 \fBupperBound\fP\fC [get, private set]\fP"
.br
.in -1c
.SH "构造及析构函数说明"
.PP 
.SS "Physics\&.Collision\&.Model\&.AABB\&.AABB (Vector3 lowerBound, Vector3 upperBound)\fC [inline]\fP"

.SH "成员函数说明"
.PP 
.SS "void Physics\&.Collision\&.Model\&.AABB\&.Apply (Vector3 lower, Vector3 upper)\fC [inline]\fP"

.SH "属性说明"
.PP 
.SS "Vector3 Physics\&.Collision\&.Model\&.AABB\&.lowerBound\fC [get]\fP, \fC [private set]\fP"

.SS "Vector3 Physics\&.Collision\&.Model\&.AABB\&.upperBound\fC [get]\fP, \fC [private set]\fP"


.SH "作者"
.PP 
由 Doyxgen 通过分析 PhysicsWorld 的 源代码自动生成\&.
