.TH "Physics.Collision.Model" 3 "2022年 十一月 2日 星期三" "PhysicsWorld" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Physics.Collision.Model
.SH SYNOPSIS
.br
.PP
.SS "类"

.in +1c
.ti -1c
.RI "class \fBAABB\fP"
.br
.ti -1c
.RI "class \fBEdge\fP"
.br
.ti -1c
.RI "class \fBSimplexEdge\fP"
.br
.in -1c
.SS "枚举"

.in +1c
.ti -1c
.RI "enum \fBAABBProjectionType\fP { \fBHorizontalStart\fP, \fBHorizontalEnd\fP, \fBVerticalStart\fP, \fBVerticalEnd\fP }"
.br
.in -1c
.SH "枚举类型说明"
.PP 
.SS "enum \fBPhysics\&.Collision\&.Model\&.AABBProjectionType\fP"

.PP
\fB枚举值\fP
.in +1c
.TP
\fB\fIHorizontalStart \fP\fP
.TP
\fB\fIHorizontalEnd \fP\fP
.TP
\fB\fIVerticalStart \fP\fP
.TP
\fB\fIVerticalEnd \fP\fP
.SH "作者"
.PP 
由 Doyxgen 通过分析 PhysicsWorld 的 源代码自动生成\&.
