.TH "Physics.Collision.Model.Edge" 3 "2022年 十一月 4日 星期五" "PhysicsWorld" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Physics.Collision.Model.Edge
.SH SYNOPSIS
.br
.PP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "Vector3 \fBa\fP"
.br
.ti -1c
.RI "Vector3 \fBb\fP"
.br
.ti -1c
.RI "Vector3 \fBnormal\fP"
.br
.ti -1c
.RI "float \fBdistance\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.in -1c
.SH "类成员变量说明"
.PP 
.SS "Vector3 Physics\&.Collision\&.Model\&.Edge\&.a"

.SS "Vector3 Physics\&.Collision\&.Model\&.Edge\&.b"

.SS "float Physics\&.Collision\&.Model\&.Edge\&.distance"

.SS "int Physics\&.Collision\&.Model\&.Edge\&.index"

.SS "Vector3 Physics\&.Collision\&.Model\&.Edge\&.normal"


.SH "作者"
.PP 
由 Doyxgen 通过分析 PhysicsWorld 的 源代码自动生成\&.
