.TH "Physics.Collision" 3 "2022年 十一月 4日 星期五" "PhysicsWorld" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Physics.Collision
.SH SYNOPSIS
.br
.PP
.SS "命名空间"

.in +1c
.ti -1c
.RI "namespace \fBModel\fP"
.br
.ti -1c
.RI "namespace \fBShape\fP"
.br
.in -1c
.SS "类"

.in +1c
.ti -1c
.RI "class \fBCollisionObject\fP"
.br
.ti -1c
.RI "interface \fBICollisionObject\fP"
.br
.ti -1c
.RI "class \fBProjectionPoint\fP"
.br
.in -1c
.SS "枚举"

.in +1c
.ti -1c
.RI "enum \fBCollisionFlags\fP { \fBDefault\fP = 0, \fBStaticObject\fP = 1, \fBNoContactResponse\fP = 2 }"
.br
.in -1c
.SH "枚举类型说明"
.PP 
.SS "enum \fBPhysics\&.Collision\&.CollisionFlags\fP"

.PP
\fB枚举值\fP
.in +1c
.TP
\fB\fIDefault \fP\fP
.TP
\fB\fIStaticObject \fP\fP
.TP
\fB\fINoContactResponse \fP\fP
.SH "作者"
.PP 
由 Doyxgen 通过分析 PhysicsWorld 的 源代码自动生成\&.
