.TH "Physics.IPhysicsWorld" 3 "2022年 十一月 2日 星期三" "PhysicsWorld" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Physics.IPhysicsWorld
.SH SYNOPSIS
.br
.PP
.PP
被 \fBPhysics\&.PhysicsWorld\fP 继承\&.
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "bool \fBAddCollisionObject\fP (\fBCollisionObject\fP collisionObject)"
.br
.ti -1c
.RI "bool \fBRemoveCollisionObject\fP (\fBCollisionObject\fP collisionObject)"
.br
.in -1c
.SH "成员函数说明"
.PP 
.SS "bool Physics\&.IPhysicsWorld\&.AddCollisionObject (\fBCollisionObject\fP collisionObject)"

.PP
在 \fBPhysics\&.PhysicsWorld\fP 内被实现\&.
.SS "bool Physics\&.IPhysicsWorld\&.RemoveCollisionObject (\fBCollisionObject\fP collisionObject)"

.PP
在 \fBPhysics\&.PhysicsWorld\fP 内被实现\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 PhysicsWorld 的 源代码自动生成\&.
