.TH "Physics.Collision.Shape" 3 "2022年 十一月 4日 星期五" "PhysicsWorld" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Physics.Collision.Shape
.SH SYNOPSIS
.br
.PP
.SS "类"

.in +1c
.ti -1c
.RI "class \fBCircle\fP"
.br
.ti -1c
.RI "class \fBCollisionShape\fP"
.br
.ti -1c
.RI "class \fBCustomShape\fP"
.br
.ti -1c
.RI "class \fBRect\fP"
.br
.in -1c
.SS "枚举"

.in +1c
.ti -1c
.RI "enum \fBShapeType\fP { \fBUndefined\fP, \fBRect\fP, \fBCircle\fP, \fBCustom\fP }"
.br
.in -1c
.SH "枚举类型说明"
.PP 
.SS "enum \fBPhysics\&.Collision\&.Shape\&.ShapeType\fP"

.PP
\fB枚举值\fP
.in +1c
.TP
\fB\fIUndefined \fP\fP
.TP
\fB\fIRect \fP\fP
.TP
\fB\fICircle \fP\fP
.TP
\fB\fICustom \fP\fP
.SH "作者"
.PP 
由 Doyxgen 通过分析 PhysicsWorld 的 源代码自动生成\&.
