.TH "/Users/zhuangshaokun/Documents/git/campfire/2dcollisiondetection/Assets/Scripts/PhysicsWorld.cs" 3 "2022年 十一月 4日 星期五" "PhysicsWorld" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/zhuangshaokun/Documents/git/campfire/2dcollisiondetection/Assets/Scripts/PhysicsWorld.cs
.SH SYNOPSIS
.br
.PP
.SS "类"

.in +1c
.ti -1c
.RI "interface \fBPhysics\&.IPhysicsWorld\fP"
.br
.ti -1c
.RI "class \fBPhysics\&.PhysicsWorld\fP"
.br
.in -1c
.SS "命名空间"

.in +1c
.ti -1c
.RI "namespace \fBPhysics\fP"
.br
.in -1c
.SS "类型定义"

.in +1c
.ti -1c
.RI "using \fBCollisionFlags\fP = \fBPhysics\&.Collision\&.CollisionFlags\fP"
.br
.ti -1c
.RI "using \fBDebug\fP = UnityEngine\&.Debug"
.br
.ti -1c
.RI "using \fBRandom\fP = UnityEngine\&.Random"
.br
.in -1c
.SH "类型定义说明"
.PP 
.SS "using \fBCollisionFlags\fP =  \fBPhysics\&.Collision\&.CollisionFlags\fP"

.SS "using \fBDebug\fP =  UnityEngine\&.Debug"

.SS "using \fBRandom\fP =  UnityEngine\&.Random"

.SH "作者"
.PP 
由 Doyxgen 通过分析 PhysicsWorld 的 源代码自动生成\&.
