.TH "Physics.Collision.ProjectionPoint" 3 "2022年 十一月 2日 星期三" "PhysicsWorld" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Physics.Collision.ProjectionPoint
.SH SYNOPSIS
.br
.PP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBProjectionPoint\fP (\fBCollisionObject\fP \fBcollisionObject\fP, \fBAABBProjectionType\fP \fBprojectionType\fP)"
.br
.in -1c
.SS "Public 属性"

.in +1c
.ti -1c
.RI "\fBCollisionObject\fP \fBcollisionObject\fP"
.br
.ti -1c
.RI "\fBAABBProjectionType\fP \fBprojectionType\fP"
.br
.in -1c
.SS "属性"

.in +1c
.ti -1c
.RI "float \fBvalue\fP\fC [get]\fP"
.br
.in -1c
.SS "Private 成员函数"

.in +1c
.ti -1c
.RI "void \fBUpdateProjectionPoint\fP ()"
.br
.in -1c
.SS "Private 属性"

.in +1c
.ti -1c
.RI "float \fB_value\fP"
.br
.in -1c
.SH "构造及析构函数说明"
.PP 
.SS "Physics\&.Collision\&.ProjectionPoint\&.ProjectionPoint (\fBCollisionObject\fP collisionObject, \fBAABBProjectionType\fP projectionType)\fC [inline]\fP"

.SH "成员函数说明"
.PP 
.SS "void Physics\&.Collision\&.ProjectionPoint\&.UpdateProjectionPoint ()\fC [inline]\fP, \fC [private]\fP"

.SH "类成员变量说明"
.PP 
.SS "float Physics\&.Collision\&.ProjectionPoint\&._value\fC [private]\fP"

.SS "\fBCollisionObject\fP Physics\&.Collision\&.ProjectionPoint\&.collisionObject"

.SS "\fBAABBProjectionType\fP Physics\&.Collision\&.ProjectionPoint\&.projectionType"

.SH "属性说明"
.PP 
.SS "float Physics\&.Collision\&.ProjectionPoint\&.value\fC [get]\fP"


.SH "作者"
.PP 
由 Doyxgen 通过分析 PhysicsWorld 的 源代码自动生成\&.
