.TH "Physics.Collision.Shape.CustomShape" 3 "2022年 十一月 2日 星期三" "PhysicsWorld" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Physics.Collision.Shape.CustomShape
.SH SYNOPSIS
.br
.PP
.PP
继承自 \fBPhysics\&.Collision\&.Shape\&.CollisionShape\fP \&.
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBCustomShape\fP (Vector3[] \fBlocalVertices\fP)"
.br
.in -1c
.SS "Protected 成员函数"

.in +1c
.ti -1c
.RI "override void \fBGetBound\fP (out Vector3 lowerBound, out Vector3 upperBound)"
.br
.in -1c
.SS "额外继承的成员函数"
.SH "构造及析构函数说明"
.PP 
.SS "Physics\&.Collision\&.Shape\&.CustomShape\&.CustomShape (Vector3[] localVertices)\fC [inline]\fP"

.SH "成员函数说明"
.PP 
.SS "override void Physics\&.Collision\&.Shape\&.CustomShape\&.GetBound (out Vector3 lowerBound, out Vector3 upperBound)\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
实现了 \fBPhysics\&.Collision\&.Shape\&.CollisionShape\fP\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 PhysicsWorld 的 源代码自动生成\&.
