.TH "Physics.Test.CollisionObjectProxy" 3 "2022年 十一月 4日 星期五" "PhysicsWorld" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Physics.Test.CollisionObjectProxy
.SH SYNOPSIS
.br
.PP
.PP
继承自 MonoBehaviour \&.
.SS "Public 属性"

.in +1c
.ti -1c
.RI "\fBCollisionObject\fP \fBtarget\fP"
.br
.ti -1c
.RI "\fBShapeType\fP \fBshape\fP"
.br
.ti -1c
.RI "bool \fBisInControl\fP = false"
.br
.ti -1c
.RI "int \fBnP\fP = 1"
.br
.ti -1c
.RI "float \fBvelocity\fP = 7"
.br
.in -1c
.SS "Private 成员函数"

.in +1c
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.in -1c
.SH "成员函数说明"
.PP 
.SS "void Physics\&.Test\&.CollisionObjectProxy\&.Update ()\fC [inline]\fP, \fC [private]\fP"

.SH "类成员变量说明"
.PP 
.SS "bool Physics\&.Test\&.CollisionObjectProxy\&.isInControl = false"

.SS "int Physics\&.Test\&.CollisionObjectProxy\&.nP = 1"

.SS "\fBShapeType\fP Physics\&.Test\&.CollisionObjectProxy\&.shape"

.SS "\fBCollisionObject\fP Physics\&.Test\&.CollisionObjectProxy\&.target"

.SS "float Physics\&.Test\&.CollisionObjectProxy\&.velocity = 7"


.SH "作者"
.PP 
由 Doyxgen 通过分析 PhysicsWorld 的 源代码自动生成\&.
